title: EnkonDelta
description: Welcome to the Map 3.0 Project
remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
baseurl: "/EnkonDelta"
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
